# Generated by Django 5.2.15 on 2026-06-19 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(help_text='The date this attendance belongs to')),
                ('check_in_at', models.DateTimeField(blank=True, null=True)),
                ('check_in_latitude', models.FloatField(blank=True, null=True)),
                ('check_in_longitude', models.FloatField(blank=True, null=True)),
                ('check_in_distance', models.FloatField(blank=True, help_text='Distance from office in meters at check-in', null=True)),
                ('face_image_in', models.ImageField(blank=True, null=True, upload_to='face_punches/in/')),
                ('check_out_at', models.DateTimeField(blank=True, null=True)),
                ('check_out_latitude', models.FloatField(blank=True, null=True)),
                ('check_out_longitude', models.FloatField(blank=True, null=True)),
                ('check_out_distance', models.FloatField(blank=True, help_text='Distance from office in meters at check-out', null=True)),
                ('face_image_out', models.ImageField(blank=True, null=True, upload_to='face_punches/out/')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half Day'), ('ON_LEAVE', 'On Leave')], default='PRESENT', max_length=20)),
                ('total_hours', models.FloatField(blank=True, help_text='Total working hours', null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Attendance Log',
                'verbose_name_plural': 'Attendance Logs',
                'ordering': ['-work_date', '-check_in_at'],
                'unique_together': {('employee', 'work_date')},
            },
        ),
    ]
