# Generated by Django 5.2.15 on 2026-06-19 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Morning Shift, Night Shift', max_length=100)),
                ('start_time', models.TimeField(help_text='Shift start time')),
                ('end_time', models.TimeField(help_text='Shift end time')),
                ('grace_period_minutes', models.PositiveIntegerField(default=15, help_text='Grace period in minutes after shift start before marking LATE')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(help_text='Shift assignment start date')),
                ('effective_to', models.DateField(blank=True, help_text='Shift assignment end date (blank = ongoing)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='employees.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='shifts.shift')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
    ]
