# Generated by Django 5.2.15 on 2026-06-19 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HRReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(help_text='Type of report, e.g., attendance, compensation', max_length=100)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('data', models.JSONField(default=dict, help_text='Arbitrary report data')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HR Report',
                'verbose_name_plural': 'HR Reports',
                'ordering': ['-generated_at'],
            },
        ),
    ]
